### ISSUE TITLE
Convert found result to TDict

### ISSUE THREAD

**Issue by oblalex** [vandersonmota/t_dict#2]
Hello!

How about converting found result to `TDict` if it's a `dict`?

It would be really convenient to use in templates, e.g. in Jinja2:

    {% set meteorology = data.find('/conditions/meteorology') %}
    {% if meteorology %}
        {{ meteorology.find('/wind/direction') }} m/s
    {%  endif %}

Thanks!

**Comment by vandersonmota** [comment]
nice one. Will implement it soon

**Comment by vandersonmota** [comment]
done 00c8a51

**Comment by o3bvv** [comment]
Cool, thanks!
